# .github/actions/print-message/action.yml
name: "Print Message Action"
description: "A simple action to print a message and greet a person."
inputs:
  name:
    description: "The name of the person to greet"
    required: true
    default: "World"
  message:
    description: "A custom message to print"
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo the greeting
      shell: bash
      run: |
        echo "Hello, ${{ inputs.name }}!"

    - name: Print the custom message
      shell: bash
      run: |
        echo "Message: ${{ inputs.message }}"
