name: Greet User Workflow

on:
  push:
    branches: 
      - 'master'

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run combined composite action
        uses: ./.github/actions/testing-action
        with:
          message: "Welcome to our project"
          name: "koshmarik"

  # Job to call the reusable workflow
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      message: "Hello from reusable workflow!"

  remote-reusable-workflow:
    uses: xXkoshmarikXx/reusable-workflow-test/workflows/main.yml@master
    with:
      message: "Hello from remote reusable workflow!"