name: Greet User Workflow

on:
  push:
    branches: 
      - 'master'

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Echo Greeting Action
        uses: ./.github/actions/testing-action
        with:
          name: 'koshmarik'

  # Job to call the composite action
  call-combined-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run combined composite action
        uses: ./.github/actions/testing-action
        with:
          name: "koshmarik"
          message: "Welcome to our project!"

  # Job to call the reusable workflow
  call-reusable-workflow:
    uses: .github/workflows/reusable-workflow.yml
    with:
      message: "Hello from reusable workflow!"